### ISSUE TITLE
Event Processor

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/cf-google-analytics#1]
This is created. Not tested.

Need to test:
* [x] Processor is available
* [x] Processor UI works
* [x] Validates properly
* [x] Doesn't break form submission if either event is not used.
* [x] Load event is sent to Google whenever form is loaded (pretty sure this isn't going to happen unless submission completes)
* [x] Form submission event sends to google when set and form submission is complete.
* [x] Load event is not sent to Google when not configured.
* [x] Form submission event is not sent to Google when not configured.

**Comment by Shelob9** [comment]
@vinnycaldera Please leave a comment with the commit hash that resolves this.

**Comment by vinnycaldera** [comment]
Commit: 9f89e8dd866210dfd84f2f940ac65b1cc0650165

**Comment by lchski** [comment]
@Shelob9 what kind of validation are you looking for?

**Comment by vinnycaldera** [comment]
I meant the form validation. My concern is that the two events are
optional. Does submitting the form with out one of them setup stop the form
from submitting?

**Comment by Shelob9** [comment]
@lchski  I meant that since both events are optional, I don't want not setting one up to stop form validation, which it 100% will.

See: https://github.com/CalderaWP/Caldera-Forms/issues/746

Workaround:
https://github.com/CalderaWP/edd-sl-plus/blob/master/classes/cf/init.php#L138-L144

**Comment by Shelob9** [comment]
100% might be an overstatement, "probably will" is better, but something to look out for is that if a form field is bound to a processor field, the form field becomes required whether it was set by user to be required or not, which is sensible, but full of gotcha.

**Comment by lchski** [comment]
I think we’re good! Also, the load event *does* send to GA on form load, regardless of whether the form submits.
