### ISSUE TITLE
eCommerce Processor

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/cf-google-analytics#2]
This is created. Not tested.

Need to test:
* [x] Processor is available
* [x] Processor UI works
* [x] Validates properly
* [x] Doesn't break form submission if not used.
* [x] Transaction total is sent to Google.
* [x] Individual items are sent to Google when the filter is used.

**Comment by lchski** [comment]
This should be good, feature-wise, as of 89d55b13c57b65b1e50fe105aafa8b674039bf9d. The code could be cleaned up a bit, and I can take a pass at that soon.

**Comment by lchski** [comment]
Just did some cleaning with 80db6b5ed1ba8d1a15ff7e5ecc3e6d9c5a1a1612. More could be done, probably, but it’s a start.

**Comment by lchski** [comment]
@Shelob9 this looks good to go, and works when used at the same time as #1.
